# Generated by Django 4.2.27 on 2026-01-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Изображение'),
        ),
    ]
