# Generated by Django 4.2.27 on 2026-01-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_historicalproject_image_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpriority',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(default='#6c757d', max_length=7, verbose_name='Цвет'),
        ),
    ]
